video_name: "Block01-2024-02-28-15-06-34-538"
video_path: "/data/JBCS_paper/ds1/val/{video_name}/video.mp4"
annotation_path: "/data/JBCS_paper/ds1/clicks/"
save_dirs: "/data/JBCS_paper/ds1/val/{video_name}/maps/"

human_attention:
  model_path: "./saved_models/ViNet_DHF1K.pt"